### ISSUE TITLE
Fit Artboard to Contents without dialog

### ISSUE THREAD

**Issue by patrickplaggenborg** [romannurik/Figma-ArtboardTricks#10]
Love this plugin! Use the Sketch version daily, and very happy to see it in Figma as well.

When I use `Fit Artboard to Contents` it pops up a dialog box for padding.

I would like to use it without any dialog box. So I can bind a keyboard shortcut and use it instantly without any disruption.

Would it be possible to move those padding settings to preferences so using the command can be instant?

<img width="343" alt="padding dialog" src="https://user-images.githubusercontent.com/2269563/115014236-560d1f80-9eb2-11eb-8a34-4f630b8f15e7.png">

**Comment by romannurik** [comment]
Hey there! There's actually a built-in command + keyboard shortcut in Figma if all you need is to resize to fit without any padding: "Resize to fit", on Mac it's ⌥⇧⌘R

**Comment by patrickplaggenborg** [comment]
Yeah I found out later indeed.

That should be fine for me, as I don’t use the padding feature.

Thanks!

**Comment by romannurik** [comment]
Awesome!
